"""The extraction guards — what counts as a successfully extracted section.

Run:  uv run python tests/test_extract_sections.py

WHY THIS FILE EXISTS
--------------------
CLAUDE.md: "A silently empty extraction is worse than a crash." The character floor
in config/sections.toml was the only thing enforcing that, and it asks the wrong
question — "did we get any bytes?" — which a document published as images passes
while containing nothing readable.

The real case, found by the verification suite (VERIFICATION.md D6): the FY2024
dividend press release is 163 characters, cleared the 120-character whole-document
floor, and was recorded `ok: true` with `problems: []`. Its entire content is two
JPG filenames and a Workiva generator stamp. One of 231, and it cost nothing because
the same announcement was captured from the 8-K body — but SPEC.md puts 7.01/8.01
strategic exhibits in scope, and a strategic exhibit published as images would have
disappeared exactly the same way, silently.

Both directions are tested. A floor that rejects real documents is worse than no
floor, because the failure list stops being read — so the legitimately short filings
in this window (an 82-word SEC comment letter, a 166-word CORRESP reply) are pinned
here as must-pass cases alongside the defect as a must-fail case.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
for _s in (sys.stdout, sys.stderr):
    if hasattr(_s, "reconfigure"):
        _s.reconfigure(encoding="utf-8", errors="replace")

import extract_sections as e  # noqa: E402

PASS = FAIL = 0


def check(name: str, got, want) -> None:
    global PASS, FAIL
    if got == want:
        PASS += 1
        print(f"  ok    {name}")
    else:
        FAIL += 1
        print(f"  FAIL  {name}\n          got  {got!r}\n          want {want!r}")


CFG = {"sections": tomllib.loads(
    (ROOT / "config" / "sections.toml").read_text(encoding="utf-8"))}
FLOOR = CFG["sections"]["validation"]["min_substantive_words"]

# THE DEFECT, verbatim from
# data/sections/FY2024/8-K/0001289419-24-000014/8-K_EX-99-1_whole.txt
IMAGE_ONLY = (
    "EX-99.1 2 dividendpr_031524v2.htm EX-99.1 Document generated by Workiva Inc "
    "dividendpr_031524v2\ndividendpr_031524v2001.jpg\n1 of 2\n"
    "dividendpr_031524v2002.jpg\n2 of 2\n")

# A legitimately short document from the same window: the SEC's completion-of-review
# letter (0000000000-24-002242), 82 substantive words. It MUST pass.
SHORT_BUT_REAL = (
    "February 28, 2024\n\nUnited States securities and exchange commission logo\n\n"
    "Jason Dubinsky\nChief Financial Officer\nMorningstar, Inc.\n"
    "22 West Washington Street\nChicago, IL 60602\n\nRe: Morningstar, Inc.\n\n"
    "Form 10-K for the Fiscal Year Ended December 31, 2022\nFile No. 000-51280\n\n"
    "Dear Jason Dubinsky:\n\n We have completed our review of your filing. We remind "
    "you that the company and its management are responsible for the accuracy and "
    "adequacy of their disclosures, notwithstanding any review, comments, action or "
    "absence of action by the staff. Please contact the staff member listed below "
    "with any questions about this letter or our review.\n\nSincerely,\n"
    "Division of Corporation Finance\nOffice of Finance\n")


print("substantive_words — characters can lie, words cannot")
check("image filenames are not words", e.substantive_words(IMAGE_ONLY), 12)
check("  and the character count that hid it is comfortably above the byte floor",
      len(IMAGE_ONLY) > 120, True)
check("a real but short SEC letter is well clear of the floor",
      e.substantive_words(SHORT_BUT_REAL) > FLOOR, True)
check("a filename-only blob counts as almost nothing — '1 of 3' contributes only 'of'",
      e.substantive_words("a001.jpg b002.jpg c003.png\n1 of 3\n"), 1)
check("  digits are never words, however many of them there are",
      e.substantive_words("1 2 3 45 678 9,012 34.56"), 0)
check("single letters are not words (column markers, list bullets)",
      e.substantive_words("a b c d e f g h i j k l m n o p q r s t u v w x y z"), 0)
check("prose about images still counts as prose",
      e.substantive_words(
          "The chart below shows revenue growth across every reportable segment "
          "during the period under review, together with the related commentary "
          "management provided in the accompanying discussion. chart001.jpg") > FLOOR,
      True)


print("\nvalidate — the guard fires on the defect and not on the real documents")
ok, problems = e.validate("8-K_EX-99-1_whole", IMAGE_ONLY, CFG, whole_doc=True)
check("the image-only exhibit is NOT ok", ok, False)
check("  and says so in terms that name the cause",
      any(p.startswith("NO USABLE TEXT") and "image" in p for p in problems), True)
check("  which is what it used to report", (True, []) != (ok, problems), True)

ok2, problems2 = e.validate("UPLOAD_LETTER_whole", SHORT_BUT_REAL, CFG, whole_doc=True)
check("the legitimately short SEC letter is still ok", ok2, True)
check("  with nothing reported against it", problems2, [])

# A section extraction landing on a page of images fails identically. The guard is
# not restricted to whole documents: there is no kind of section for which 25
# readable words is a successful read.
ok3, problems3 = e.validate("10-K_item1_business", IMAGE_ONLY, CFG, whole_doc=False)
check("a SECTION with no usable text fails too, not just a whole document",
      ok3, False)
check("  and reports the no-text problem, not only the character floor",
      any(p.startswith("NO USABLE TEXT") for p in problems3), True)


print("\nthe manifest on disk records the class, if sections have been extracted")
import json  # noqa: E402
mp = ROOT / "data" / "sections" / "sections-manifest.json"
if mp.exists():
    man = json.loads(mp.read_text(encoding="utf-8"))
    listed = man.get("sections_with_no_usable_text", [])
    check("no-usable-text sections are a named category, not folded into failures",
          isinstance(listed, list), True)
    # Every row in that category must actually be marked not-ok, or the category is
    # decorative and the section is still reachable by anything reading `ok`.
    bad = [r for r in man["sections"]
           if any(p.startswith("NO USABLE TEXT") for p in (r.get("problems") or []))
           and r.get("ok")]
    check("  and every one of them is ok=False, so nothing downstream can cite it",
          bad, [])
    check("  the category and the flagged rows agree",
          len(listed),
          sum(1 for r in man["sections"]
              if any(p.startswith("NO USABLE TEXT") for p in (r.get("problems") or []))))
else:
    print("  --    no sections-manifest.json; skipped")

print(f"\n{PASS} passed, {FAIL} failed")
sys.exit(1 if FAIL else 0)
