"""The extraction guards — what counts as a successfully extracted section.

Run:  uv run python tests/test_extract_sections.py

WHY THIS FILE EXISTS
--------------------
CLAUDE.md: "A silently empty extraction is worse than a crash." The character floor
in config/sections.toml was the only thing enforcing that, and it asks the wrong
question — "did we get any bytes?" — which a document published as images passes
while containing nothing readable.

The real case, found by the verification suite (VERIFICATION.md D6): the FY2024
dividend press release is 163 characters, cleared the 120-character whole-document
floor, and was recorded `ok: true` with `problems: []`. Its entire content is two
JPG filenames and a Workiva generator stamp. One of 231, and it cost nothing because
the same announcement was captured from the 8-K body — but SPEC.md puts 7.01/8.01
strategic exhibits in scope, and a strategic exhibit published as images would have
disappeared exactly the same way, silently.

Both directions are tested. A floor that rejects real documents is worse than no
floor, because the failure list stops being read — so the legitimately short filings
in this window (an 82-word SEC comment letter, a 166-word CORRESP reply) are pinned
here as must-pass cases alongside the defect as a must-fail case.
"""

from __future__ import annotations

import sys
import tomllib

for _s in (sys.stdout, sys.stderr):
    if hasattr(_s, "reconfigure"):
        _s.reconfigure(encoding="utf-8", errors="replace")

# ROOT from the package rather than counted off __file__, so this file survives
# being moved. The stage module below still resolves a ticker at IMPORT time from
# EQR_TICKER — run_all supplies it — but nothing here reads that company's data;
# `config/sections.toml` is global, shared by every company, which is why these
# checks are unit checks and the manifest ones are not.
from equity_research.paths import ROOT  # noqa: E402
import equity_research.extract_sections as e  # noqa: E402

PASS = FAIL = 0


def check(name: str, got, want) -> None:
    global PASS, FAIL
    if got == want:
        PASS += 1
        print(f"  ok    {name}")
    else:
        FAIL += 1
        print(f"  FAIL  {name}\n          got  {got!r}\n          want {want!r}")


CFG = {"sections": tomllib.loads(
    (ROOT / "config" / "sections.toml").read_text(encoding="utf-8"))}
FLOOR = CFG["sections"]["validation"]["min_substantive_words"]

# THE DEFECT, verbatim from
# data/sections/FY2024/8-K/0001289419-24-000014/8-K_EX-99-1_whole.txt
IMAGE_ONLY = (
    "EX-99.1 2 dividendpr_031524v2.htm EX-99.1 Document generated by Workiva Inc "
    "dividendpr_031524v2\ndividendpr_031524v2001.jpg\n1 of 2\n"
    "dividendpr_031524v2002.jpg\n2 of 2\n")

# A legitimately short document from the same window: the SEC's completion-of-review
# letter (0000000000-24-002242), 82 substantive words. It MUST pass.
SHORT_BUT_REAL = (
    "February 28, 2024\n\nUnited States securities and exchange commission logo\n\n"
    "Jason Dubinsky\nChief Financial Officer\nMorningstar, Inc.\n"
    "22 West Washington Street\nChicago, IL 60602\n\nRe: Morningstar, Inc.\n\n"
    "Form 10-K for the Fiscal Year Ended December 31, 2022\nFile No. 000-51280\n\n"
    "Dear Jason Dubinsky:\n\n We have completed our review of your filing. We remind "
    "you that the company and its management are responsible for the accuracy and "
    "adequacy of their disclosures, notwithstanding any review, comments, action or "
    "absence of action by the staff. Please contact the staff member listed below "
    "with any questions about this letter or our review.\n\nSincerely,\n"
    "Division of Corporation Finance\nOffice of Finance\n")


print("substantive_words — characters can lie, words cannot")
check("image filenames are not words", e.substantive_words(IMAGE_ONLY), 12)
check("  and the character count that hid it is comfortably above the byte floor",
      len(IMAGE_ONLY) > 120, True)
check("a real but short SEC letter is well clear of the floor",
      e.substantive_words(SHORT_BUT_REAL) > FLOOR, True)
check("a filename-only blob counts as almost nothing — '1 of 3' contributes only 'of'",
      e.substantive_words("a001.jpg b002.jpg c003.png\n1 of 3\n"), 1)
check("  digits are never words, however many of them there are",
      e.substantive_words("1 2 3 45 678 9,012 34.56"), 0)
check("single letters are not words (column markers, list bullets)",
      e.substantive_words("a b c d e f g h i j k l m n o p q r s t u v w x y z"), 0)
check("prose about images still counts as prose",
      e.substantive_words(
          "The chart below shows revenue growth across every reportable segment "
          "during the period under review, together with the related commentary "
          "management provided in the accompanying discussion. chart001.jpg") > FLOOR,
      True)


print("\nvalidate — the guard fires on the defect and not on the real documents")
ok, problems = e.validate("8-K_EX-99-1_whole", IMAGE_ONLY, CFG, whole_doc=True)
check("the image-only exhibit is NOT ok", ok, False)
check("  and says so in terms that name the cause",
      any(p.startswith("NO USABLE TEXT") and "image" in p for p in problems), True)
check("  which is what it used to report", (True, []) != (ok, problems), True)

ok2, problems2 = e.validate("UPLOAD_LETTER_whole", SHORT_BUT_REAL, CFG, whole_doc=True)
check("the legitimately short SEC letter is still ok", ok2, True)
check("  with nothing reported against it", problems2, [])

# A section extraction landing on a page of images fails identically. The guard is
# not restricted to whole documents: there is no kind of section for which 25
# readable words is a successful read.
ok3, problems3 = e.validate("10-K_item1_business", IMAGE_ONLY, CFG, whole_doc=False)
check("a SECTION with no usable text fails too, not just a whole document",
      ok3, False)
check("  and reports the no-text problem, not only the character floor",
      any(p.startswith("NO USABLE TEXT") for p in problems3), True)


# The three checks that read sections-manifest.json — that no-usable-text is a
# named category, that every row in it is ok=False, and that the category and the
# rows agree — moved to tests/regression/morn/test_cache.py in Phase 5.1. They
# were guarded by `if mp.exists()` and printed "skipped" otherwise, so in a clean
# checkout this file silently ran 14 checks instead of 17 and reported success.


# ---------------------------------------------------------------------------
# choose_documents — one rendition per role per filing
# ---------------------------------------------------------------------------
# Added Phase 6.4, after MSFT's FY2020 proxy demonstrated the defect live: the
# `.htm` extracted four sections cleanly, the `.pdf` of the SAME document under
# the SAME accession then failed all four, and because the manifest merges on
# (accession, key) the failures replaced the successes. Manifest said
# "0 ok, 4 failed" while the good text sat on disk.
#
# Named companies appear below only as the provenance of each shape; every input
# is inline and nothing here reads a company's data.

def doc(acc, doc_type, filename, form="DEF 14A", fy=2020, size=1_000_000):
    return {"accession": acc, "doc_type": doc_type, "filename": filename,
            "form": form, "fiscal_year": fy, "bytes": size,
            "filing_date": f"{fy}-10-19"}


print("\nchoose_documents — the HTML rendition wins, and only where there is a choice")

# THE DEFECT'S EXACT SHAPE. MSFT FY2020, accession 0001193125-20-272025.
pair = [doc("A1", "DEF 14A", "d31295ddef14a.htm", size=1_880_000),
        doc("A1", "DEF 14A", "d31295ddef14a1.pdf", size=9_350_000)]
kept, dropped = e.choose_documents(pair)
check("two renditions of one proxy collapse to one document", len(kept), 1)
check("  and it is the HTML one", kept[0]["filename"], "d31295ddef14a.htm")
check("  with the PDF reported as superseded, not silently gone", len(dropped), 1)
check("  naming the PDF", dropped[0]["filename"], "d31295ddef14a1.pdf")

# Order in the manifest must not decide the outcome — the PDF is listed first
# here, and MSFT's real manifest lists it first too (it is the larger file).
kept2, _ = e.choose_documents(list(reversed(pair)))
check("PDF-listed-first gives the same answer", kept2[0]["filename"],
      "d31295ddef14a.htm")

# PREFER, NEVER SKIP. MORN's FY2022 ARS is a PDF with no HTML sibling and it
# extracts fine; dropping it would delete the shareholder letter for that year.
solo_pdf = [doc("B1", "ARS", "tm2310844d1_ars.pdf", form="ARS", fy=2022)]
kept3, dropped3 = e.choose_documents(solo_pdf)
check("a PDF with no HTML sibling is KEPT", len(kept3), 1)
check("  and nothing is reported superseded", dropped3, [])

# Roles within one filing are distinct and all wanted: MSFT's FY2025 10-K
# carries the 10-K plus EX-10.7 and EX-10.8.
tenk = [doc("C1", "10-K", "msft-20250630.htm", form="10-K", fy=2025),
        doc("C1", "EX-10.7", "msft-ex10_7.htm", form="10-K", fy=2025),
        doc("C1", "EX-10.8", "msft-ex10_8.htm", form="10-K", fy=2025)]
kept4, dropped4 = e.choose_documents(tenk)
check("exhibits are separate roles and all survive", len(kept4), 3)
check("  nothing superseded among them", dropped4, [])

# An UPLOAD carries a LETTER (PDF) and a TEXT-EXTRACT (TXT) — different roles,
# both kept, which is the behaviour MORN's committed ledger already depends on.
upload = [doc("D1", "LETTER", "filename1.pdf", form="UPLOAD"),
          doc("D1", "TEXT-EXTRACT", "filename2.txt", form="UPLOAD")]
kept5, dropped5 = e.choose_documents(upload)
check("an UPLOAD's PDF letter and text extract both survive", len(kept5), 2)
check("  neither superseded, despite one being a PDF", dropped5, [])

# Different accessions are different filings even for the same role: MSFT files
# a DEF 14A and several DEFA14A supplements in the same month.
two_filings = [doc("E1", "DEF 14A", "a.htm"), doc("E2", "DEF 14A", "b.htm")]
kept6, dropped6 = e.choose_documents(two_filings)
check("same role in DIFFERENT filings is not a collision", len(kept6), 2)
check("  nothing superseded", dropped6, [])

# Caller ordering is preserved, so the run log and the manifest stay readable
# and a re-run picks the same document (CLAUDE.md rule 4).
mixed = [doc("F1", "DEF 14A", "p.pdf", fy=2021), doc("F1", "DEF 14A", "h.htm", fy=2021),
         doc("F2", "10-K", "k.htm", form="10-K", fy=2022)]
kept7, _ = e.choose_documents(mixed)
check("kept documents come back in the caller's order",
      [r["filename"] for r in kept7], ["h.htm", "k.htm"])
check("choosing twice gives an identical answer",
      [r["filename"] for r in e.choose_documents(mixed)[0]],
      [r["filename"] for r in kept7])

# Non-HTML ranks equal on purpose: among two non-HTML candidates the manifest's
# own order decides, and this function invents no ranking it was never measured
# against. Pinned so a later "improvement" to rendition_rank has to face it.
two_nonhtml = [doc("G1", "ARS", "first.pdf", form="ARS"),
               doc("G1", "ARS", "second.txt", form="ARS")]
check("two non-HTML candidates: the first listed wins, stably",
      e.choose_documents(two_nonhtml)[0][0]["filename"], "first.pdf")

check("rendition_rank ranks HTML above everything else",
      [e.rendition_rank(f) for f in ("a.htm", "a.html", "a.xhtml", "a.pdf", "a.txt")],
      [0, 0, 0, 1, 1])
check("  and is case-insensitive about the suffix",
      e.rendition_rank("A.HTM"), 0)

# The empty case, because a --form/--fy filter can select nothing.
check("no documents in, no documents out", e.choose_documents([]), ([], []))


# ---------------------------------------------------------------------------
# extract_10k — choosing among heading candidates
# ---------------------------------------------------------------------------
# Added Phase 6.4. The rule was "first surviving occurrence of each item number",
# which is right only where something else already removed the table of contents.
# MORN's TOC is a list of hyperlinks and `find_item_heading_candidates` drops
# those, so the rule looked general for five years and one company. MSFT's TOC is
# a plain table with no anchors, and every 10-K section for six years came back as
# a TOC row of about 58 characters.
#
# Synthetic documents below, small enough to read. `FLOOR` is deliberately tiny so
# the fixtures stay legible; the real floor is validation.min_chars.

import tempfile  # noqa: E402
from pathlib import Path  # noqa: E402

FLOOR = 200
_tmp = Path(tempfile.mkdtemp())
_n = [0]


def doc_from(html: str) -> "e.Doc":
    """A parsed Doc from inline HTML. Doc takes a path, so write one."""
    _n[0] += 1
    p = _tmp / f"d{_n[0]}.htm"
    p.write_text(f"<html><body>{html}</body></html>", encoding="utf-8")
    return e.Doc(p)


def body(item: str, title: str, words: int) -> str:
    return (f"<p><b>Item {item}. {title}</b></p>"
            + f"<p>{'substantive prose about the business ' * words}</p>")


# MSFT's shape: a TOC built as a table, item number and title in separate cells,
# page numbers alongside, and NOT hyperlinked.
TOC_TABLE = (
    "<table>"
    "<tr><td>Item 1.</td><td>Business</td><td>3</td></tr>"
    "<tr><td>Item 1A.</td><td>Risk Factors</td><td>19</td></tr>"
    "<tr><td>Item 7.</td><td>Management's Discussion and Analysis</td><td>35</td></tr>"
    "<tr><td>Item 7A.</td><td>Quantitative Disclosures</td><td>53</td></tr>"
    "<tr><td>Item 8.</td><td>Financial Statements</td><td>55</td></tr>"
    "</table>")

print("\nextract_10k — the table-of-contents trap")

msft_like = doc_from(
    TOC_TABLE
    + body("1", "Business", 40)
    + body("1A", "Risk Factors", 40)
    + body("7", "Management's Discussion and Analysis", 40)
    + body("7A", "Quantitative Disclosures", 1)     # genuinely below the floor
    + body("8", "Financial Statements", 40))
got = e.extract_10k(msft_like, FLOOR)

check("a non-hyperlinked TOC no longer wins Item 1",
      got["10-K_item1_business"]["text"].startswith("Item 1. Business"), True)
check("  and the captured span is the body, not a TOC row",
      got["10-K_item1_business"]["chars"] if "chars" in got["10-K_item1_business"]
      else len(got["10-K_item1_business"]["text"]) > FLOOR, True)
check("  with no page number from the TOC row in it",
      "19" in got["10-K_item1_business"]["text"][:40], False)
check("Item 1A likewise", got["10-K_item1a_risk_factors"]["text"]
      .startswith("Item 1A. Risk Factors"), True)
check("Item 7 likewise", got["10-K_item7_mdna"]["text"]
      .startswith("Item 7. Management"), True)
check("the basis records that a choice was made, and on what",
      "to reach" in got["10-K_item1_business"]["boundary_basis"], True)

# THE FALLBACK, and why it is largest-span rather than first. Item 7A's real
# section is one sentence, below the floor, so no candidate clears it. Choosing
# 7A's TOC row would put the chosen node BEFORE Item 7's body heading, and Item 7
# would then run past 7A into Item 8 — which is exactly what MSFT's MD&A did.
# The span is [i0, i1), so the terminating heading is EXCLUDED — "stops at 7A"
# means 7A's own heading node IS the end index, not that its text is included.
_c7a = [i for num, i in e.find_item_heading_candidates(msft_like) if num == "7A"]
check("Item 7A has both a TOC row and a body heading in this fixture",
      len(_c7a), 2)
check("Item 7 ends exactly AT 7A's BODY heading, below-floor or not",
      got["10-K_item7_mdna"]["node_range"][1], max(_c7a))
check("  which is NOT 7A's table-of-contents row",
      got["10-K_item7_mdna"]["node_range"][1] == min(_c7a), False)
check("  so 7A's own heading text is not inside Item 7",
      "Quantitative Disclosures" in got["10-K_item7_mdna"]["text"], False)
check("  and Item 7 does not reach Item 8",
      "Financial Statements" in got["10-K_item7_mdna"]["text"], False)

# MORN's shape: the TOC is a list of anchors, which is removed before selection.
morn_like = doc_from(
    "<div>"
    '<a href="#i1">Item 1. Business</a>'
    '<a href="#i1a">Item 1A. Risk Factors</a>'
    '<a href="#i7">Item 7. Management\'s Discussion and Analysis</a>'
    "</div>"
    + body("1", "Business", 40)
    + body("1A", "Risk Factors", 40)
    + body("7", "Management's Discussion and Analysis", 40))
got2 = e.extract_10k(morn_like, FLOOR)
check("a hyperlinked TOC is still filtered before selection",
      got2["10-K_item1_business"]["text"].startswith("Item 1. Business"), True)
check("  and with one candidate left the basis says so",
      got2["10-K_item1_business"]["boundary_basis"].endswith("(sole candidate)"),
      True)

# A missing item is reported, not silently skipped.
partial = doc_from(body("1", "Business", 40) + body("2", "Properties", 40))
got3 = e.extract_10k(partial, FLOOR)
check("a missing item is an error, not an empty section",
      "error" in got3["10-K_item1a_risk_factors"], True)
check("  and the error names what WAS found",
      "1" in got3["10-K_item1a_risk_factors"]["error"], True)
check("a document with no item headings yields nothing at all",
      e.extract_10k(doc_from("<p>no headings here</p>"), FLOOR), {})

# Determinism: the same document twice gives the same node ranges.
check("choosing twice gives the same boundaries",
      [got[k]["node_range"] for k in sorted(got)],
      [e.extract_10k(msft_like, FLOOR)[k]["node_range"] for k in sorted(got)])

# find_item_headings keeps its old contract for any other caller.
check("find_item_headings still returns first-occurrence-per-item",
      [n for n, _ in e.find_item_headings(msft_like)][:3], ["1", "1A", "7"])
check("find_item_heading_candidates returns MORE than one per item",
      len([1 for n, _ in e.find_item_heading_candidates(msft_like) if n == "1"]), 2)


# ---------------------------------------------------------------------------
# extract_letter — a letter that ends without a formal closing
# ---------------------------------------------------------------------------
# Added Phase 6.4. The four configured closings (best regards / sincerely /
# respectfully / warm regards) were verified against four documents from ONE
# company. MSFT's three letters contain none of them — zero matches across
# 276,000 characters each — because a modern CEO letter often closes on the
# signature alone. Uses the REAL config, so these exercise the shipped patterns
# rather than a copy of them that could drift.

print("\nextract_letter — no formal closing, and the bound on the fallback")

LO, HI = e._letter_bounds(CFG)
check("the fallback's bounds come from validation.expected_chars", (LO, HI),
      (CFG["sections"]["validation"]["expected_chars"]["letter_full_text"]["min"],
       CFG["sections"]["validation"]["expected_chars"]["letter_full_text"]["max"]))

PROSE = "We are living through a time of historic challenge and opportunity. " * 40


def letter(closing: str, after: str = "") -> str:
    return f"Dear shareholders, colleagues, and partners:\n\n{PROSE}\n{closing}{after}"


# MORN's shape: a formal closing, the name AFTER it.
signed_off = letter("Best regards,\n\nKunal\n")
got_a = e.extract_letter(signed_off, CFG)
check("a letter with a formal closing still uses the sign-off path",
      "-> sign-off" in got_a["boundary_basis"], True)
check("  and the tail reaches the name that follows the closing",
      "Kunal" in got_a["text"], True)

# MSFT's shape: no closing at all, a signature block instead.
NEXT_SECTION = "\f\nISSUER PURCHASES OF EQUITY SECURITIES, DIVIDENDS\n\nOur common stock"
signed_only = letter("Satya Nadella\nChairman and Chief Executive Officer\n"
                     "October 15, 2025\n\n5\n", NEXT_SECTION)
got_b = e.extract_letter(signed_only, CFG)
check("a letter with NO closing is still found, via the signature",
      "error" in got_b, False)
check("  and the basis says which rule fired",
      "signature (no formal closing" in got_b["boundary_basis"], True)
check("  the signer's name is inside the letter", "Satya Nadella" in got_b["text"],
      True)
check("  and the title too", "Chief Executive Officer" in got_b["text"], True)
check("  the page break trims the next section back out",
      "ISSUER PURCHASES" in got_b["text"], False)
check("  so no financial-section heading leaks in",
      "common stock" in got_b["text"], False)

# THE BOUND, which is the whole reason the fallback is safe. MORN's FY2022 annual
# report has a signature at char 620,214 of 621,612; accepting it would capture
# the entire 10-K and the financial statements.
far_away = (letter("") + "X" * (HI + 5_000)
            + "\nKunal Kapoor\nChief Executive Officer\n")
got_c = e.extract_letter(far_away, CFG)
check("a signature far beyond the expected length is REJECTED", "error" in got_c,
      True)
check("  and the error says a signature was considered and why it lost",
      "signature block yielding" in got_c["error"], True)

# Nothing at all to end on.
got_d = e.extract_letter(letter(""), CFG)
check("no closing and no signature is still a loud failure", "error" in got_d, True)
check("  naming the sign-off patterns that were tried",
      "sincerely" in got_d["error"], True)

# No salutation -> the earlier error, unchanged.
got_e = e.extract_letter("Some annual report with no greeting at all. " * 20, CFG)
check("no salutation reports that, not a signature problem",
      got_e.get("error", "").startswith("no salutation found"), True)

# The sign-off path must NOT be trimmed at a page break. This pins a DELIBERATE
# DECISION rather than an ideal: MORN's FY2022 letter is the one PDF among its
# four, its signature is followed by a form feed, and trimming there would drop
# the trailing page footer — a real improvement of 50 characters that is NOT taken
# because the unit has two committed facts and both shipped deliverables cite
# FY2022 ids. See the comment in extract_letter.
#
# Asserting on the FOOTER, not on the signer's name: "Kunal" sits before the form
# feed, so it survives either way and cannot tell the two behaviours apart. That
# was this check's first form, and the MORN enforcer caught an ungated trim that
# this file missed.
pdf_signoff = letter("Best regards,\n\nKunal\n", "\f\nMorningstar, Inc. Annual Report")
got_f = e.extract_letter(pdf_signoff, CFG)
check("the signer's name survives the sign-off path", "Kunal" in got_f["text"], True)
check("a form feed does NOT trim the sign-off path's tail",
      "Morningstar, Inc. Annual Report" in got_f["text"], True)

print(f"\n{PASS} passed, {FAIL} failed")
sys.exit(1 if FAIL else 0)
