"""Milestone 5d — render output/timeline.md.

DETERMINISTIC. No model call, and that is a deliberate design decision rather than a
shortcut, so it is worth stating plainly.

---------------------------------------------------------------------------
WHY THIS DOCUMENT IS NOT GENERATED BY A MODEL
---------------------------------------------------------------------------
SPEC.md section 4b asks for a "reference document, not prose" — a chronological table
of dated events where "every row carries a source". Every field that table needs
already exists in the ledger: date, date precision, type, description, source ids,
confidence, and how many filings corroborate the row.

So the only thing a model could add is rewriting the descriptions. Measured, the
median description is 161 characters and the longest is 375 — already table length.
And a rewritten description would be a paraphrase OF a paraphrase: `claim` text is
itself model-written and unverified (only 3.1% of it appears verbatim in its own
quote), so condensing it puts the reader two steps from the filing with no check
possible at either step.

Against that, a deterministic render cannot fabricate a date, drop a row, or drift a
description — and it asserts its own completeness before writing: every input row
appears in exactly one table or the run fails.

The cost saving is incidental. If the model added something checkable it would be
worth $0.30. It doesn't.

The judgment calls the ledger cannot make are all made upstream in
src/equity_research/merge_events.py, where they are config-driven, tested, and auditable — which is
the right place for them.

Run it:
    uv run python -m equity_research.render_timeline
    uv run python -m equity_research.render_timeline --stdout

Writes:
    output/timeline.md
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from collections import Counter
from datetime import datetime, timezone

from equity_research import settings
from equity_research._bootstrap import ROOT
from equity_research.merge_events import timeline_block
from equity_research.paths import add_ticker_arg, paths

# Every data/ and output/ path for the company this run operates on.
# `paths()` resolves the ticker from --ticker, then EQR_TICKER, then the
# single company under companies/ -- see equity_research/paths.py.
P = paths()

PACK_DIR = P.pack
OUT_DIR = P.output
CONFIG = P.config_dir / "outputs.toml"

for _s in (sys.stdout, sys.stderr):
    if hasattr(_s, "reconfigure"):
        _s.reconfigure(encoding="utf-8", errors="replace")

# Rendered date precision. A month-precision date must not print as though the day
# were known — the filing said "July 2022", not the 1st.
MONTHS = ["", "January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]


def pretty_date(date: str, precision: str | None) -> str:
    if precision == "day":
        y, m, d = date.split("-")
        return f"{int(d)} {MONTHS[int(m)][:3]} {y}"
    if precision == "month":
        y, m = date.split("-")
        return f"{MONTHS[int(m)]} {y}"
    return date


def esc(s: str) -> str:
    """Markdown table cells cannot contain a bare pipe."""
    return s.replace("|", "\\|").replace("\n", " ").strip()


def subject() -> dict:
    """Company identity from the ledger, never from config.

    config/company.toml carries a `resolved_name` tripwire rather than an input, so
    the authoritative name is whatever discovery resolved and the ledger recorded.
    """
    p = sorted(P.ledger.glob("FY*.json"))
    if not p:
        sys.exit("FATAL: no ledger. Run `uv run python -m equity_research.build_ledger` first.")
    years = [json.loads(x.read_text(encoding="utf-8")) for x in p]
    return {"ticker": years[0]["ticker"], "name": years[0]["company_name"],
            "cik": years[0]["cik"],
            "fys": sorted(y["fiscal_year"] for y in years)}


def source_cell(row: dict) -> str:
    """Ids first, then the filings. The id is the citable handle; the accession is
    what a human opens on EDGAR."""
    ids = " ".join(f"`{i}`" for i in row["ids"])
    accs = ", ".join(sorted({s.split("|")[0] + " " + s.split("|")[1]
                             for s in row["sources"] if "|" in s}))
    return f"{ids}<br>{accs}" if accs else ids


def flags(row: dict, say_on_pay: list[re.Pattern], conflict_ids: set[str]) -> str:
    out = []
    if row.get("predates_window"):
        out.append("*(predates the window)*")
    if conflict_ids & set(row["ids"]):
        out.append("‡")
    if row["corroborating_filings"] > 1:
        out.append(f"**×{row['corroborating_filings']} filings**")
    if row.get("types_disagree"):
        out.append("**types disagree:** " + "/".join(row["types_disagree"]))
    if row["confidence"] != "high":
        out.append(f"**{row['confidence']} confidence**")
    if any(p.search(row["description"]) for p in say_on_pay):
        out.append("†")
    return " ".join(out)


def table(rows: list[dict], say_on_pay: list[re.Pattern], conflict_ids: set[str],
          dated: bool = True) -> list[str]:
    head = (["| Date | Type | Event | Source |", "|---|---|---|---|"] if dated
            else ["| FY | Type | Event | Source |", "|---|---|---|---|"])
    out = list(head)
    for r in rows:
        first = (pretty_date(r["date"], r["date_precision"]) if dated
                 else f"FY{r['fiscal_years'][0]}")
        note = flags(r, say_on_pay, conflict_ids)
        desc = esc(r["description"]) + (f" {note}" if note else "")
        out.append(f"| {first} | {(r['type'] or 'other').replace('_', ' ')} | "
                   f"{desc} | {source_cell(r)} |")
    return out


def render() -> str:
    cfg = tomllib.loads(CONFIG.read_text(encoding="utf-8"))["timeline"]
    say_on_pay = [re.compile(p) for p in cfg["say_on_pay_patterns"]]
    block = timeline_block(include_quotes=False)
    s = subject()
    c = block["counts"]

    # Named `conf` rather than `c`: `c` is already the counts dict above. Python
    # comprehensions have their own scope so this would not actually have leaked, but a
    # reader should not have to know that to be sure.
    conflict_ids = {i for conf in block.get("date_conflicts", []) for i in conf["ids"]}

    dated_material = [r for r in block["dated"] if not r["routine"]]
    dated_routine = [r for r in block["dated"] if r["routine"]]
    unclear = block["period_unclear"]

    # COMPLETENESS, ASSERTED BEFORE WRITING. The three tables below must between them
    # contain every row, exactly once. A timeline that quietly lost a row would look
    # completely normal — it would just be short, and nobody counts.
    rendered = [r for grp in (dated_material, dated_routine, unclear) for r in grp]
    ids_in = {i for r in block["dated"] + unclear for i in r["ids"]}
    ids_out = [i for r in rendered for i in r["ids"]]
    if len(rendered) != c["rows_after_merge"] or sorted(ids_out) != sorted(ids_in):
        sys.exit(f"FATAL: the render would not be complete.\n"
                 f"  {c['rows_after_merge']} rows in, {len(rendered)} rendered; "
                 f"{len(ids_in)} ids in, {len(set(ids_out))} out.\n"
                 f"  missing: {sorted(ids_in - set(ids_out))[:5]}")

    # The stamped input file, which `src/equity_research/merge_events.py` writes. `timeline_block()`
    # above recomputes the rows in memory, so the render itself does not need the file
    # — but the document records its input's hash, and a missing input must say which
    # stage produces it rather than raising a bare FileNotFoundError from a rebuild.
    events = P.timeline_events
    if not events.exists():
        sys.exit(f"FATAL: {events.relative_to(ROOT)} not found.\n"
                 f"  Build it first: uv run python -m equity_research.merge_events")
    src_hash = hashlib.sha256(events.read_bytes()).hexdigest()

    L: list[str] = [
        f"# {s['name']} ({s['ticker']}) — Timeline, FY{s['fys'][0]}–FY{s['fys'][-1]}",
        "",
        "Dated events drawn from the company's SEC filings. Every row carries the fact "
        "id it came from and the filing that reported it; nothing here was written from "
        "outside the filings.",
        "",
        f"**{len(dated_material)}** material dated events · **{len(dated_routine)}** "
        f"routine governance · **{len(unclear)}** events the filings did not date · "
        f"**{c['corroborated']}** corroborated by more than one filing",
        "",
        "### How to read this", "",
        "- **Date precision varies.** A row shown as *July 2022* is month-precision — "
        "the filing gave no day, and it must not be read as the 1st.",
        "- **`×2 filings`** means two or more filings independently reported that event. "
        "That is corroboration; both ids are listed.",
        "- **Source ids** resolve in `data/pack/index.json` to the exact quote and "
        "section the row rests on.",
        f"- **{c['predates_window']} rows predate FY{s['fys'][0]}** and are marked "
        f"*(predates the window)*. In-scope filings describe them — the FY{s['fys'][0]} "
        f"10-K discusses a 2019 credit agreement — so they are real and sourced, and are "
        f"marked rather than dropped."
        if c["predates_window"] else
        "- Every dated row falls inside the window.",
        # Conditional, because a legend explaining a marker that appears nowhere in
        # the document tells the reader to go looking for something that is not there.
        ("- **‡** marks a row that more than one filing dates differently. Whether the "
         "filings settle which date is which is stated per event in the notes at the end."
         if conflict_ids else
         "- **No event in this document carries conflicting dates across filings.**"),
        "- Every row in this document is `high` confidence." if all(
            r["confidence"] == "high" for r in rendered) else
        "- Rows marked **low confidence** rest on a fact whose section boundaries are "
        "unverified or whose quote could not be confirmed.",
        "",
        "## Material events", "",
    ]
    L += table(dated_material, say_on_pay, conflict_ids)

    L += ["", "## Routine governance", "",
          "Annual-meeting outcomes and regular dividend declarations. Separated rather "
          "than omitted, so the chronology above stays skimmable without anything being "
          "dropped from the record.", ""]
    L += table(dated_routine, say_on_pay, conflict_ids)
    if any(any(p.search(r["description"]) for p in say_on_pay) for r in dated_routine):
        L += ["",
              "† **The advisory vote concerns the PRIOR fiscal year's compensation.** The "
              "date shown is the meeting date, which is correct as printed — but a vote "
              "held in May of year N approves the pay awarded for year N−1. Do not "
              "attribute a say-on-pay result to the year it was voted in."]

    L += ["", "## Events the filings did not date", "",
          "These are real events. They appear here rather than in the chronology because "
          "no filing gave a usable date, and assigning one — the filing's own date, say — "
          "would place them wrongly: a 10-K filed in February reports things that "
          "happened the previous year. Ordered by the fiscal year whose filings reported "
          "them.", ""]
    L += table(unclear, say_on_pay, conflict_ids, dated=False)

    L += ["", "## Notes on this document", "",
          f"- **Merge rule.** {block['merge_rule']}. Records from the same filing are "
          f"never merged at any similarity: a filing does not report the same event "
          f"twice. {c['records_absorbed']} records folded into {c['corroborated']} rows.",
          ]
    if block["possible_duplicates_not_merged"]:
        L += [f"- **{len(block['possible_duplicates_not_merged'])} same-date pairs were "
              f"left unmerged** below the similarity threshold. Both are a credit "
              f"agreement against its own covenant terms:"]
        for p in block["possible_duplicates_not_merged"]:
            L += [f"    - {p['similarity']:.0f} on {p['date']}: "
                  f"*{esc(p['a']['description'][:90])}…* vs "
                  f"*{esc(p['b']['description'][:90])}…*"]
    if block.get("undated_near_duplicates_not_merged"):
        L += ["- **Undated rows are never merged**, whatever their wording. Among them "
              "the two closest pairs are 1.5 points apart and fall on opposite sides of "
              "the truth — one is a single impairment reported twice, the other is two "
              "different years of dividend guidance whose wording is templated. Both are "
              "left as separate rows:"]
        for p in block["undated_near_duplicates_not_merged"]:
            L += [f"    - {p['similarity']:.0f}: *{esc(p['a']['description'][:90])}…* vs "
                  f"*{esc(p['b']['description'][:90])}…*"]
    if block.get("date_conflicts"):
        # The note is READ OFF the conflict record rather than re-composed here.
        #
        # This block used to restate the "the filings do not settle it" sentence in
        # its own words, a second hardcoded copy of an assertion about evidence the
        # renderer had never seen. Both copies were wrong about Bevin Desmond's
        # departure, in a document whose whole claim is that it contains nothing the
        # ledger does not. `find_date_conflicts` examines the filings and writes the
        # note; the renderer's job is to print it. See VERIFICATION.md D1.
        confs = block["date_conflicts"]
        n_settled = sum(1 for c in confs if c.get("resolved"))
        head = (f"- **‡ {len(confs)} event{'' if len(confs) == 1 else 's'} carry more "
                f"than one date across filings**, over {len(conflict_ids)} rows above. "
                f"Every row is kept in every case; what differs is whether the filings "
                f"settle which date is which")
        head += (f" — {n_settled} of {len(confs)} do:" if n_settled else ", and none do:")
        L += [head]
        for conf in confs:
            mark = "**settled**" if conf.get("resolved") else "**unsettled**"
            L += [f"    - {mark} — *{esc(conf['description'][:110])}*, dated "
                  f"{' and '.join(conf['dates'])} across {len(conf['filings'])} filings. "
                  f"{esc(conf['note'])}"]
    L += [f"- **{c['input_records']} ledger records** (event and leadership facts) "
          f"produced these {c['rows_after_merge']} rows. Completeness is asserted at "
          f"render time: every input id appears in exactly one table above, or this file "
          f"is not written."]

    L += ["", "---", "",
          f"Built by `src/equity_research/render_timeline.py` — deterministic, no "
          f"model call, so this document contains nothing the ledger does not, and "
          f"re-running reproduces it byte for byte. The provenance that matters is "
          f"the input hash below, not a clock; when it last ran is recorded in "
          f"`data/_meta/run-log.json`.",
          "",
          f"Input `data/pack/timeline-events.json` sha256 `{src_hash[:32]}`. "
          f"{s['name']}, CIK {s['cik']}.", ""]
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser(description="Milestone 5d — render output/timeline.md.")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    add_ticker_arg(ap)

    args = ap.parse_args()

    text = render()
    if args.stdout:
        print(text)
        return

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = P.timeline_md
    path.write_text(text, encoding="utf-8")
    settings.record_run(P, "render_timeline", chars=len(text))

    block = timeline_block(include_quotes=False)
    c = block["counts"]
    rows = block["dated"] + block["period_unclear"]
    print(f"wrote {path.relative_to(ROOT)}")
    print(f"  {len(text.splitlines())} lines, {len(text):,} chars")
    print(f"  {c['rows_after_merge']} rows: "
          f"{sum(1 for r in block['dated'] if not r['routine'])} material, "
          f"{sum(1 for r in block['dated'] if r['routine'])} routine, "
          f"{c['period_unclear']} undated")
    print(f"  types: {dict(Counter((r['type'] or 'other') for r in rows).most_common())}")
    print("  no model call; $0.00")


if __name__ == "__main__":
    main()
